In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder

import warnings
warnings.filterwarnings("ignore")

In [4]:
original_df = pd.read_csv('apartments_for_rent_classified_10K_utf.csv')

In [5]:
df = original_df[["amenities", "bathrooms", "bedrooms", "fee", "price", "price_type", "square_feet", "cityname", "state", "time"]]

In [6]:
df.head(5)

,amenities,bathrooms,bedrooms,fee,price,price_type,square_feet,cityname,state,time
0,NaN,NaN,0.0,No,790,Monthly,101,Washington,DC,1577359415
1,NaN,NaN,1.0,No,425,Monthly,106,Evansville,IN,1577017063
2,NaN,1.0,0.0,No,1390,Monthly,107,Arlington,VA,1577359410
3,NaN,1.0,0.0,No,925,Monthly,116,Seattle,WA,1576667743
4,NaN,NaN,0.0,No,880,Monthly,125,Arlington,VA,1577359401

In [7]:
df.isna().mean()

amenities      0.3549
bathrooms      0.0034
bedrooms       0.0007
fee            0.0000
price          0.0000
price_type     0.0000
square_feet    0.0000
cityname       0.0077
state          0.0077
time           0.0000
dtype: float64

## Convert timestamp to datetime objects

In [8]:
df['time'] = pd.to_datetime(df['time'], unit='s')

In [9]:
df.head(2)

,amenities,bathrooms,bedrooms,fee,price,price_type,square_feet,cityname,state,time
0,NaN,NaN,0.0,No,790,Monthly,101,Washington,DC,2019-12-26 11:23:35
1,NaN,NaN,1.0,No,425,Monthly,106,Evansville,IN,2019-12-22 12:17:43

## Normalizing Price and Square Feet

Convert any prices measured in Weeks to Months by converting to price per day then price per year then price per month (roughly 4.348 multiplier).

There is one abnormally high price with 'weekly' price_type. The price for 'week' is 1560, and digging into the dataset, we found that it is a duplicate of index 15. The listing is for the same place except it's on another listing website. This duplicate will be dropped in favor of the other one.

There is also one record with 'Monthly|Weekely' price_type with a price of 275.0, and the price is likely to be on a weekly basis.

In [10]:
df[df['price'] == 1560][:2]

,amenities,bathrooms,bedrooms,fee,price,price_type,square_feet,cityname,state,time
15,"AC,Basketball,Cable or Satellite,Gym,Internet ...",1.0,1.0,No,1560,Weekly,200,New Bern,NC,2019-12-17 21:27:56
16,"AC,Basketball,Cable or Satellite,Gym,Internet ...",1.0,1.0,No,1560,Monthly,200,New Bern,NC,2019-12-15 10:37:53

In [11]:
df = df.drop([16,17])

In [12]:
df[df['price_type'] == 'Monthly|Weekly']

,amenities,bathrooms,bedrooms,fee,price,price_type,square_feet,cityname,state,time
235,"Cable or Satellite,Pool,Refrigerator,Storage,TV",NaN,NaN,No,275,Monthly|Weekly,300,Lakeland,FL,2019-11-27 21:43:20

In [13]:
for i in df.index:
  if (df['price_type'][i] == "Weekly") or (df['price_type'][i] == "Monthly/Weekly"):
    df.loc[i, 'price'] = df['price'][i] / 7 * 365.25 / 12

df['price'] = (df['price'] - df['price'].min()) / (df['price'].max() - df['price'].min())

In [14]:
print(df['price'].min())
print(df['price'].max())

0.0
1.0

Since we have standardized the units of the price, we can drop the price_type column.

In [15]:
df = df.drop(columns=['price_type'])

## Normalize the square_feet using Min Max method

In [16]:
df['square_feet'] = (df['square_feet'] - df['square_feet'].min()) / (df['square_feet'].max() - df['square_feet'].min())

In [17]:
print(df['square_feet'].min())
print(df['square_feet'].max())

0.0
1.0

## Impute NaN values using median

In [18]:
df['bathrooms'] = df['bathrooms'].replace({np.nan: df['bathrooms'].median()})

In [19]:
df['bedrooms'] = df['bedrooms'].replace({np.nan: df['bedrooms'].median()})

## Preprocessing on the amenities

In [20]:
df['amenities'] = np.array(df['amenities'].str.strip().str.split(","))

In [21]:
df

,amenities,bathrooms,bedrooms,fee,price,square_feet,cityname,state,time
0,NaN,1.0,0.0,No,0.011281,0.000000,Washington,DC,2019-12-26 11:23:35
1,NaN,1.0,1.0,No,0.004302,0.000125,Evansville,IN,2019-12-22 12:17:43
2,NaN,1.0,0.0,No,0.022753,0.000150,Arlington,VA,2019-12-26 11:23:30
3,NaN,1.0,0.0,No,0.013862,0.000376,Seattle,WA,2019-12-18 11:15:43
4,NaN,1.0,0.0,No,0.013002,0.000602,Arlington,VA,2019-12-26 11:23:21
...,...,...,...,...,...,...,...,...,...
9995,NaN,4.0,5.0,No,0.110899,0.155367,Edina,MN,2019-11-30 11:22:55
9996,NaN,8.0,6.0,No,0.474187,0.215920,Montecito,CA,2019-12-26 11:40:19
9997,NaN,8.5,6.0,No,0.206501,0.281135,Potomac,MD,2019-12-26 11:42:40
9998,"[Basketball, Cable or Satellite, Doorman, Hot ...",1.0,1.0,No,0.087763,1.000000,New York,NY,2019-12-26 12:09:46
9999,"[Gym, Patio/Deck]",1.0,1.0,No,0.015468,0.019524,Lawrenceville,GA,2019-12-26 12:09:01

In [22]:
df['amenities'] = df['amenities'].replace({np.nan: 'None'})

In [23]:
df.head(5)

,amenities,bathrooms,bedrooms,fee,price,square_feet,cityname,state,time
0,None,1.0,0.0,No,0.011281,0.000000,Washington,DC,2019-12-26 11:23:35
1,None,1.0,1.0,No,0.004302,0.000125,Evansville,IN,2019-12-22 12:17:43
2,None,1.0,0.0,No,0.022753,0.000150,Arlington,VA,2019-12-26 11:23:30
3,None,1.0,0.0,No,0.013862,0.000376,Seattle,WA,2019-12-18 11:15:43
4,None,1.0,0.0,No,0.013002,0.000602,Arlington,VA,2019-12-26 11:23:21

## One-hot Encoding States and City Names
States and city names are nominal categorical features. To deal with this, we will be creating one-hot encoded fields to reflect each data points location.

In [24]:
all_states = df['state'].unique()
all_states

array(['DC', 'IN', 'VA', 'WA', 'NY', 'CA', 'AZ', 'NC', 'GA', 'FL', nan,
       'AL', 'MD', 'CO', 'NM', 'IL', 'TN', 'AK', 'MA', 'NJ', 'OR', 'DE',
       'PA', 'TX', 'IA', 'SC', 'MN', 'MI', 'KY', 'WI', 'OH', 'CT', 'RI',
       'NV', 'UT', 'MO', 'OK', 'NH', 'NE', 'LA', 'ND', 'AR', 'KS', 'ID',
       'HI', 'MT', 'VT', 'SD', 'WV', 'MS', 'ME', 'WY'], dtype=object)

In [25]:
display(df['state'].value_counts())

display(df['cityname'].value_counts())

TX    1736
CA     955
WA     519
NC     437
MD     424
NJ     383
GA     372
FL     339
OH     321
CO     318
WI     302
IL     282
IN     239
MO     239
MN     221
VA     205
OR     197
PA     183
IA     179
OK     178
MI     176
MA     167
AZ     126
NV     121
ND     113
NE     105
CT      98
TN      92
UT      84
KS      83
DC      80
SC      77
NY      71
NH      70
SD      66
LA      66
AL      56
AR      56
AK      44
KY      40
ID      21
VT      16
NM      14
HI      12
RI      11
MS       9
MT       7
DE       5
WV       3
ME       2
WY       1
Name: state, dtype: int64

Austin           523
Dallas           216
Houston          186
San Antonio      182
Los Angeles      165
                ...
Clackamas          1
Keizer             1
Keyser             1
Pompano Beach      1
Bella Vista        1
Name: cityname, Length: 1574, dtype: int64

In [26]:
df = pd.get_dummies(df, columns=['state', 'cityname'], dummy_na=True)

In [27]:
df.head()

,amenities,bathrooms,bedrooms,fee,price,square_feet,time,state_AK,state_AL,state_AR,...,cityname_York,cityname_Yorktown,cityname_Yorkville,cityname_Youngstown,cityname_Youngsville,cityname_Ypsilanti,cityname_Yuba City,cityname_Yukon,cityname_Zachary,cityname_nan
0,None,1.0,0.0,No,0.011281,0.000000,2019-12-26 11:23:35,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,None,1.0,1.0,No,0.004302,0.000125,2019-12-22 12:17:43,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,None,1.0,0.0,No,0.022753,0.000150,2019-12-26 11:23:30,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,None,1.0,0.0,No,0.013862,0.000376,2019-12-18 11:15:43,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,None,1.0,0.0,No,0.013002,0.000602,2019-12-26 11:23:21,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [28]:
# extract unknown cities and states
unknown_city = df[df['cityname_nan'] == 1]
unknown_state = df[df['state_nan'] == 1]
unknown_state

# find if there is intersection between unknown cities and states
print(unknown_city.shape[0])
print(unknown_state.shape[0])
len(unknown_city.index.intersection(unknown_state.index))

77
77

77

In [29]:
df['fee'].unique()

array(['No'], dtype=object)

In [30]:
final_cleaned = df.drop(columns=['fee'])
final_cleaned

,amenities,bathrooms,bedrooms,price,square_feet,time,state_AK,state_AL,state_AR,state_AZ,...,cityname_York,cityname_Yorktown,cityname_Yorkville,cityname_Youngstown,cityname_Youngsville,cityname_Ypsilanti,cityname_Yuba City,cityname_Yukon,cityname_Zachary,cityname_nan
0,None,1.0,0.0,0.011281,0.000000,2019-12-26 11:23:35,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,None,1.0,1.0,0.004302,0.000125,2019-12-22 12:17:43,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,None,1.0,0.0,0.022753,0.000150,2019-12-26 11:23:30,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,None,1.0,0.0,0.013862,0.000376,2019-12-18 11:15:43,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,None,1.0,0.0,0.013002,0.000602,2019-12-26 11:23:21,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,None,4.0,5.0,0.110899,0.155367,2019-11-30 11:22:55,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,None,8.0,6.0,0.474187,0.215920,2019-12-26 11:40:19,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,None,8.5,6.0,0.206501,0.281135,2019-12-26 11:42:40,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,"[Basketball, Cable or Satellite, Doorman, Hot ...",1.0,1.0,0.087763,1.000000,2019-12-26 12:09:46,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9999,"[Gym, Patio/Deck]",1.0,1.0,0.015468,0.019524,2019-12-26 12:09:01,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [51]:
from keras.optimizers import SGD
from keras.models import Sequential
from keras.layers import Dense
# import keras_tuner
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(final_cleaned.drop(['price'], axis = 1), final_cleaned.price, test_size = 0.2, random_state = 42)

def buildHPmodel(hp):
  model = Sequential ([
      Dense(32, activation = 'relu', input_dim = final_cleaned.shape[1]),
      Dense(
          units = hp.Int("units", min_value = 32, max_value = 512, step = 32),
          activation = hp.Choice("activation", ["relu", "tanh"]),
      ),
      Dense(1, activation = 'sigmoid')
  ])
  learning_rate = hp.Float("lr", min_value = 1e-4, max_value = 1e-2, sampling = "log")
  model.compile(optimizer = SGD(learning_rate = learning_rate), loss = 'binary_crossentropy', metrics = ['accuracy'])
  return model

In [52]:
pip install keras_tuner

Requirement already satisfied: keras_tuner in /usr/local/lib/python3.10/dist-packages (1.4.6)
Requirement already satisfied: keras in /usr/local/lib/python3.10/dist-packages (from keras_tuner) (2.15.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from keras_tuner) (23.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from keras_tuner) (2.31.0)
Requirement already satisfied: kt-legacy in /usr/local/lib/python3.10/dist-packages (from keras_tuner) (1.0.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->keras_tuner) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->keras_tuner) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->keras_tuner) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->keras_tuner) (2024.2.2)

In [53]:
import keras_tuner

In [54]:
hp = keras_tuner.HyperParameters()

In [55]:
tuner = keras_tuner.GridSearch(
    hypermodel = buildHPmodel,
    objective = "accuracy",
    max_trials = 20,
    seed = 15,
    executions_per_trial = 5,
    tune_new_entries = True,
    allow_new_entries = True,
    max_consecutive_failed_trials = 3
)

Reloading Tuner from ./untitled_project/tuner0.json

In [56]:
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, random_state = 0)

In [57]:
tuner.search(X_train, y_train, epochs = 2, validation_data = (X_val, y_val))

In [58]:
tuner.results_summary()

Results summary
Results in ./untitled_project
Showing 10 best trials
Objective(name="accuracy", direction="max")

Trial 00 summary
Hyperparameters:
units: 32
activation: relu
lr: 0.0001
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/engine/base_tuner.py", line 273, in _try_run_and_update_trial
    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/engine/base_tuner.py", line 238, in _run_and_update_trial
    results = self.run_trial(trial, *fit_args, **fit_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/engine/tuner.py", line 314, in run_trial
    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/engine/tuner.py", line 233, in _build_and_fit_model
    results = self.hypermodel.fit(hp, model, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/engine/hypermodel.py", line 149, in fit
    return model.fit(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/constant_op.py", line 103, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).


Trial 01 summary
Hyperparameters:
units: 32
activation: relu
lr: 0.0005011872336272724
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/engine/base_tuner.py", line 273, in _try_run_and_update_trial
    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/engine/base_tuner.py", line 238, in _run_and_update_trial
    results = self.run_trial(trial, *fit_args, **fit_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/engine/tuner.py", line 314, in run_trial
    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/engine/tuner.py", line 233, in _build_and_fit_model
    results = self.hypermodel.fit(hp, model, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/engine/hypermodel.py", line 149, in fit
    return model.fit(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/constant_op.py", line 103, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).


Trial 02 summary
Hyperparameters:
units: 32
activation: relu
lr: 0.000316227766016838
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/engine/base_tuner.py", line 273, in _try_run_and_update_trial
    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/engine/base_tuner.py", line 238, in _run_and_update_trial
    results = self.run_trial(trial, *fit_args, **fit_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/engine/tuner.py", line 314, in run_trial
    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/engine/tuner.py", line 233, in _build_and_fit_model
    results = self.hypermodel.fit(hp, model, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras_tuner/src/engine/hypermodel.py", line 149, in fit
    return model.fit(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/constant_op.py", line 103, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type list).